export const LanguagesMap = {
  Afrikaans: "AFRIKAANS",
  Algerian: "ALGERIAN",
  Arabic: "ARABIC",
  Aramaic: "ARAMAIC",
  Armenian: "ARMENIAN",
  Bengali: "BENGALI",
  Berber: "BERBER",
  Bosnian: "BOSNIAN",
  Brazilian: "BRAZILIAN",
  Bulgarian: "BULGARIAN",
  Burmese: "BURMESE",
  Cantonese: "CANTONESE",
  Catalan: "CATALAN",
  Corsica: "CORSICA",
  Creole: "CREOLE",
  Croatian: "CROATIAN",
  Cypriot: "CYPRIOT",
  Czech: "CZECH",
  Danish: "DANISH",
  Dutch: "DUTCH",
  Egyptian: "EGYPTIAN",
  English: "ENGLISH",
  Esperanto: "ESPERANTO",
  Estonian: "ESTONIAN",
  Finn: "FINN",
  Finnish: "FINNISH",
  Flemish: "FLEMISH",
  French: "FRENCH",
  Georgian: "GEORGIAN",
  German: "GERMAN",
  Greek: "GREEK",
  Gypsy: "GYPSY",
  Hawaiian: "HAWAIIAN",
  Hebrew: "HEBREW",
  Hindi: "HINDI",
  Hungarian: "HUNGARIAN",
  Icelandic: "ICELANDIC",
  Indonesian: "INDONESIAN",
  Inuit: "INUIT",
  Irish: "IRISH",
  Italian: "ITALIAN",
  Japanese: "JAPANESE",
  Javanese: "JAVANESE",
  Korean: "KOREAN",
  Latin: "LATIN",
  Lithuanian: "LITHUANIAN",
  Malay: "MALAY",
  Malayalam: "MALAYALAM",
  Mandarin: "MANDARIN",
  Nepalese: "NEPALESE",
  Norwegian: "NORWEGIAN",
  Panjabi: "PANJABI",
  Polish: "POLISH",
  Portuguese: "PORTUGUESE",
  Romani: "ROMANI",
  Romanian: "ROMANIAN",
  Russian: "RUSSIAN",
  Sanskrit: "SANSKRIT",
  Scottish: "SCOTTISH",
  Serbian: "SERBIAN",
  Signlanguage: "SIGNLANGUAGE",
  Slovak: "SLOVAK",
  Slovene: "SLOVENE",
  Spanish: "SPANISH",
  Swedish: "SWEDISH",
  Tagalog: "TAGALOG",
  Tahitian: "TAHITIAN",
  Tamil: "TAMIL",
  Telugu: "TELUGU",
  Thai: "THAI",
  Tibetan: "TIBETAN",
  Turkish: "TURKISH",
  Ukrainian: "UKRAINIAN",
  Vietnamese: "VIETNAMESE",
  Welsh: "WELSH",
  Wu: "WU",
}

export const TimezonesMap = {
  "Australian Central Daylight (UTC +10:30)": "ACDT (UTC +10:30)",
  "Australian Central Standard (UTC +9:30)": "ACST (UTC +9:30)",
  "Australian Central (UTC +9:30/+10:30)": "ACT (UTC +9:30/+10:30)",
  "Australian Central Western Standard (UTC +8:45)": "ACWST (UTC +8:45)",
  "Atlantic Daylight (UTC -3)": "ADT (UTC -3)",
  "Australian Eastern Daylight (UTC +11)": "AEDT (UTC +11)",
  "Australian Eastern Standard (UTC +10)": "AEST (UTC +10)",
  "Australian Eastern (UTC +10:00/+11:00)": "AET (UTC +10:00/+11:00)",
  "Afghanistan (UTC +4:30)": "AFT (UTC +4:30)",
  "Alaska Daylight (UTC -8)": "AKDT (UTC -8)",
  "Alaska Standard (UTC -9)": "AKST (UTC -9)",
  "Alma-Ata (UTC +6)": "ALMT (UTC +6)",
  "Armenia Summer (UTC +5)": "AMST (UTC +5)",
  "Armenia (UTC +4)": "AMT (UTC +4)",
  "Anadyr Summer (UTC +12)": "ANAST (UTC +12)",
  "Anadyr (UTC +12)": "ANAT (UTC +12)",
  "Aqtobe (UTC +5)": "AQTT (UTC +5)",
  "Argentina (UTC -3)": "ART (UTC -3)",
  "Atlantic Standard (UTC -4)": "AST (UTC -4)",
  "Atlantic (UTC -4:00/-3:00)": "AT (UTC -4:00/-3:00)",
  "Australian Western Daylight (UTC +9)": "AWDT (UTC +9)",
  "Australian Western Standard (UTC +8)": "AWST (UTC +8)",
  "Azores Summer (UTC +0)": "AZOST (UTC +0)",
  "Azores (UTC -1)": "AZOT (UTC -1)",
  "Azerbaijan Summer (UTC +5)": "AZST (UTC +5)",
  "Azerbaijan (UTC +4)": "AZT (UTC +4)",
  "Brunei Darussalam (UTC +8)": "BNT (UTC +8)",
  "Bolivia (UTC -4)": "BOT (UTC -4)",
  "Brasília Summer (UTC -2)": "BRST (UTC -2)",
  "Brasília (UTC -3)": "BRT (UTC -3)",
  "British Summer (UTC +1)": "BST (UTC +1)",
  "Bhutan (UTC +6)": "BTT (UTC +6)",
  "Casey (UTC +8)": "CAST (UTC +8)",
  "Central Africa (UTC +2)": "CAT (UTC +2)",
  "Cocos Islands (UTC +6:30)": "CCT (UTC +6:30)",
  "Cuba Daylight (UTC -4)": "CDT (UTC -4)",
  "Central European Summer (UTC +2)": "CEST (UTC +2)",
  "Central European (UTC +1)": "CET (UTC +1)",
  "Chatham Island Daylight (UTC +13:45)": "CHADT (UTC +13:45)",
  "Chatham Island Standard (UTC +12:45)": "CHAST (UTC +12:45)",
  "Choibalsan Summer (UTC +9)": "CHOST (UTC +9)",
  "Choibalsan (UTC +8)": "CHOT (UTC +8)",
  "Chuuk (UTC +10)": "CHUT (UTC +10)",
  "Cayman Islands Daylight Saving (UTC -4)": "CIDST (UTC -4)",
  "Cayman Islands Standard (UTC -5)": "CIST (UTC -5)",
  "Cook Island (UTC -10)": "CKT (UTC -10)",
  "Chile Summer (UTC -3)": "CLST (UTC -3)",
  "Chile Standard (UTC -4)": "CLT (UTC -4)",
  "Colombia (UTC -5)": "COT (UTC -5)",
  "Cuba Standard (UTC -5)": "CST (UTC -5)",
  "Central (UTC -6:00/-5:00)": "CT (UTC -6:00/-5:00)",
  "Cape Verde (UTC -1)": "CVT (UTC -1)",
  "Christmas Island (UTC +7)": "CXT (UTC +7)",
  "Chamorro Standard (UTC +10)": "CHST (UTC +10)",
  "Davis (UTC +7)": "DAVT (UTC +7)",
  "Dumont-d'Urville (UTC +10)": "DDUT (UTC +10)",
  "Easter Island Summer (UTC -5)": "EASST (UTC -5)",
  "Easter Island Standard (UTC -6)": "EAST (UTC -6)",
  "Eastern Africa (UTC +3)": "EAT (UTC +3)",
  "Ecuador (UTC -5)": "ECT (UTC -5)",
  "Eastern Daylight (UTC -4)": "EDT (UTC -4)",
  "Eastern European Summer (UTC +3)": "EEST (UTC +3)",
  "Eastern European (UTC +2)": "EET (UTC +2)",
  "Eastern Greenland Summer (UTC +0)": "EGST (UTC +0)",
  "East Greenland (UTC -1)": "EGT (UTC -1)",
  "Eastern Standard (UTC -5)": "EST (UTC -5)",
  "Eastern (UTC -5:00/-4:00)": "ET (UTC -5:00/-4:00)",
  "Further-Eastern European (UTC +3)": "FET (UTC +3)",
  "Fiji Summer (UTC +13)": "FJST (UTC +13)",
  "Fiji (UTC +12)": "FJT (UTC +12)",
  "Falkland Islands Summer (UTC -3)": "FKST (UTC -3)",
  "Falkland Island (UTC -4)": "FKT (UTC -4)",
  "Fernando de Noronha (UTC -2)": "FNT (UTC -2)",
  "Galapagos (UTC -6)": "GALT (UTC -6)",
  "Gambier (UTC -9)": "GAMT (UTC -9)",
  "Georgia Standard (UTC +4)": "GET (UTC +4)",
  "French Guiana (UTC -3)": "GFT (UTC -3)",
  "Gilbert Island (UTC +12)": "GILT (UTC +12)",
  "Greenwich Mean (UTC +0)": "GMT (UTC +0)",
  "South Georgia (UTC -2)": "GST (UTC -2)",
  "Guyana (UTC -4)": "GYT (UTC -4)",
  "Hawaii-Aleutian Daylight (UTC -9)": "HDT (UTC -9)",
  "Hong Kong (UTC +8)": "HKT (UTC +8)",
  "Hovd Summer (UTC +8)": "HOVST (UTC +8)",
  "Hovd (UTC +7)": "HOVT (UTC +7)",
  "Hawaii Standard (UTC -10)": "HST (UTC -10)",
  "Indochina (UTC +7)": "ICT (UTC +7)",
  "Israel Daylight (UTC +3)": "IDT (UTC +3)",
  "Indian Chagos (UTC +6)": "IOT (UTC +6)",
  "Iran Daylight (UTC +4:30)": "IRDT (UTC +4:30)",
  "Irkutsk Summer (UTC +9)": "IRKST (UTC +9)",
  "Irkutsk (UTC +8)": "IRKT (UTC +8)",
  "Iran Standard (UTC +3:30)": "IRST (UTC +3:30)",
  "Israel Standard (UTC +2)": "IST (UTC +2)",
  "Japan Standard (UTC +9)": "JST (UTC +9)",
  "Kyrgyzstan (UTC +6)": "KGT (UTC +6)",
  "Kosrae (UTC +11)": "KOST (UTC +11)",
  "Krasnoyarsk Summer (UTC +8)": "KRAST (UTC +8)",
  "Krasnoyarsk (UTC +7)": "KRAT (UTC +7)",
  "Korea Standard (UTC +9)": "KST (UTC +9)",
  "Kuybyshev (UTC +4)": "KUYT (UTC +4)",
  "Lord Howe Daylight (UTC +11)": "LHDT (UTC +11)",
  "Lord Howe Standard (UTC +10:30)": "LHST (UTC +10:30)",
  "Line Islands (UTC +14)": "LINT (UTC +14)",
  "Magadan Summer (UTC +12)": "MAGST (UTC +12)",
  "Magadan (UTC +11)": "MAGT (UTC +11)",
  "Marquesas (UTC -9:30)": "MART (UTC -9:30)",
  "Mawson (UTC +5)": "MAWT (UTC +5)",
  "Mountain Daylight (UTC -6)": "MDT (UTC -6)",
  "Marshall Islands (UTC +12)": "MHT (UTC +12)",
  "Myanmar (UTC +6:30)": "MMT (UTC +6:30)",
  "Moscow Daylight (UTC +4)": "MSD (UTC +4)",
  "Moscow Standard (UTC +3)": "MSK (UTC +3)",
  "Mountain Standard (UTC -7)": "MST (UTC -7)",
  "Mountain (UTC -7:00/-6:00)": "MT (UTC -7:00/-6:00)",
  "Mauritius (UTC +4)": "MUT (UTC +4)",
  "Maldives (UTC +5)": "MVT (UTC +5)",
  "Malaysia (UTC +8)": "MYT (UTC +8)",
  "New Caledonia (UTC +11)": "NCT (UTC +11)",
  "Newfoundland Daylight (UTC -2:30)": "NDT (UTC -2:30)",
  "Norfolk (UTC +11)": "NFT (UTC +11)",
  "Novosibirsk Summer (UTC +7)": "NOVST (UTC +7)",
  "Novosibirsk (UTC +6)": "NOVT (UTC +6)",
  "Nepal Time UTC(+5:45)": "NPT  UTC(+5:45)",
  "Nauru (UTC +12)": "NRT (UTC +12)",
  "Newfoundland Standard (UTC -3:30)": "NST (UTC -3:30)",
  "Niue (UTC -11)": "NUT (UTC -11)",
  "New Zealand Daylight (UTC +13)": "NZDT (UTC +13)",
  "New Zealand Standard (UTC +12)": "NZST (UTC +12)",
  "Omsk Summer (UTC +7)": "OMSST (UTC +7)",
  "Omsk Standard (UTC +6)": "OMST (UTC +6)",
  "Oral (UTC +5)": "ORAT (UTC +5)",
  "Pacific Daylight (UTC -7)": "PDT (UTC -7)",
  "Peru (UTC -5)": "PET (UTC -5)",
  "Kamchatka Summer (UTC +12)": "PETST (UTC +12)",
  "Kamchatka (UTC +12)": "PETT (UTC +12)",
  "Papua New Guinea (UTC +10)": "PGT (UTC +10)",
  "Phoenix Island (UTC +13)": "PHOT (UTC +13)",
  "Philippine (UTC +8)": "PHT (UTC +8)",
  "Pakistan Standard (UTC +5)": "PKT (UTC +5)",
  "Pierre & Miquelon Daylight (UTC -2)": "PMDT (UTC -2)",
  "Pierre & Miquelon Standard (UTC -3)": "PMST (UTC -3)",
  "Pohnpei Standard (UTC +11)": "PONT (UTC +11)",
  "Pacific Standard (UTC -8)": "PST (UTC -8)",
  "Pacific (UTC -8:00/-7:00)": "PT (UTC -8:00/-7:00)",
  "Palau (UTC +9)": "PWT (UTC +9)",
  "Paraguay Summer (UTC -3)": "PYST (UTC -3)",
  "Pyongyang (UTC +8:30)": "PYT (UTC +8:30)",
  "Qyzylorda (UTC +6)": "QYZT (UTC +6)",
  "Reunion (UTC +4)": "RET (UTC +4)",
  "Rothera (UTC -3)": "ROTT (UTC -3)",
  "Sakhalin (UTC +11)": "SAKT (UTC +11)",
  "Samara (UTC +4)": "SAMT (UTC +4)",
  "South Africa Standard (UTC +2)": "SAST (UTC +2)",
  "Solomon Islands (UTC +11)": "SBT (UTC +11)",
  "Seychelles (UTC +4)": "SCT (UTC +4)",
  "Singapore (UTC +8)": "SGT (UTC +8)",
  "Srednekolymsk (UTC +11)": "SRET (UTC +11)",
  "Suriname (UTC -3)": "SRT (UTC -3)",
  "Samoa Standard (UTC -11)": "SST (UTC -11)",
  "Syowa (UTC +3)": "SYOT (UTC +3)",
  "Tahiti (UTC -10)": "TAHT (UTC -10)",
  "French Southern and Antarctic (UTC +5)": "TFT (UTC +5)",
  "Tajikistan Time (UTC +5)": "TJT (UTC +5)",
  "Tokelau (UTC +13)": "TKT (UTC +13)",
  "East Timor (UTC +9)": "TLT (UTC +9)",
  "Turkmenistan (UTC +5)": "TMT (UTC +5)",
  "Tonga Summer (UTC +14)": "TOST (UTC +14)",
  "Tonga (UTC +13)": "TOT (UTC +13)",
  "Turkey (UTC +3)": "TRT (UTC +3)",
  "Tuvalu (UTC +12)": "TVT (UTC +12)",
  "Ulaanbaatar Summer (UTC +9)": "ULAST (UTC +9)",
  "Ulaanbaatar (UTC +8)": "ULAT (UTC +8)",
  "Coordinated Universal (UTC UTC)": "UTC (UTC UTC)",
  "Uruguay Summer (UTC -2)": "UYST (UTC -2)",
  "Uruguay (UTC -3)": "UYT (UTC -3)",
  "Uzbekistan (UTC +5)": "UZT (UTC +5)",
  "Venezuelan Standard (UTC -4)": "VET (UTC -4)",
  "Vladivostok Summer (UTC +11)": "VLAST (UTC +11)",
  "Vladivostok (UTC +10)": "VLAT (UTC +10)",
  "Vostok (UTC +6)": "VOST (UTC +6)",
  "Vanuatu (UTC +11)": "VUT (UTC +11)",
  "Wake (UTC +12)": "WAKT (UTC +12)",
  "Western Argentine Summer (UTC -3)": "WARST (UTC -3)",
  "West Africa Summer (UTC +2)": "WAST (UTC +2)",
  "West Africa (UTC +1)": "WAT (UTC +1)",
  "Western European Summer (UTC +1)": "WEST (UTC +1)",
  "Western European (UTC +0)": "WET (UTC +0)",
  "Wallis and Futuna (UTC +12)": "WFT (UTC +12)",
  "Western Greenland Summer (UTC -2)": "WGST (UTC -2)",
  "West Greenland (UTC -3)": "WGT (UTC -3)",
  "Western Indonesian (UTC +7)": "WIB (UTC +7)",
  "Eastern Indonesian (UTC +9)": "WIT (UTC +9)",
  "Central Indonesian (UTC +8)": "WITA (UTC +8)",
  "Western Sahara Summer (UTC +1)": "WST (UTC +1)",
  "Western Sahara Standard (UTC +0)": "WT (UTC +0)",
  "Yakutsk Summer (UTC +10)": "YAKST (UTC +10)",
  "Yakutsk (UTC +9)": "YAKT (UTC +9)",
  "Yap (UTC +10)": "YAPT (UTC +10)",
  "Yekaterinburg Summer (UTC +6)": "YEKST (UTC +6)",
  "Yekaterinburg (UTC +5)": "YEKT (UTC +5)",
}
